spring.application.name=portfolio-backend
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

logging.level.root=INFO
logging.level.com.kevin.portfolio=INFO
logging.file.name=portfolio.log

# application.properties (or application.yml) 
# is the central configuration file for your Spring Boot application.


#Instead of hardcoding things like:
#Database URL
#Port number
#Logging levels
#JWT secrets
#Environment configs
#You externalize them into application.properties.

#Spring Boot automatically:
#Reads application.properties
#Loads values into its internal Environment
#Applies them to auto-configured components
#You don’t have to manually wire it.

