spring.datasource.url=jdbc:postgresql://dpg-d73bt3p4tr6s73dt1bv0-a:5432/portfolio_db_0kog?sslmode=require
spring.datasource.username=portfolio_db_0kog_user
spring.datasource.password=mfF5zeVrEmrJYuV8jLJ1hjo0qh6pTGSY

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

logging.level.root=INFO
logging.level.com.kevin.portfolio=INFO
logging.file.name=portfolio.log